name: Pull and process robot data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '20 15 1 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: grab and process data
      run: ./grab.sh

    - name: Commit and push if it changed
      run: |-
        git config user.name "Auto robot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
